"""Initial schema

Revision ID: 3d56651b216b
Revises: 
Create Date: 2025-12-10 18:51:32.257600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d56651b216b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('qr_code_token', sa.String(length=255), nullable=True),
    sa.Column('sharing_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{"share_periods": true, "share_ovulation": true, "share_notes": true}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('woman', 'man')", name='check_gender'),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('period_length', sa.Integer(), nullable=True),
    sa.Column('is_predicted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cycle_length IS NULL OR cycle_length > 0', name='check_cycle_length_positive'),
    sa.CheckConstraint('period_end_date IS NULL OR period_end_date >= period_start_date', name='check_period_dates'),
    sa.CheckConstraint('period_length IS NULL OR period_length > 0', name='check_period_length_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycles_period_start_date'), 'cycles', ['period_start_date'], unique=False)
    op.create_index(op.f('ix_cycles_user_id'), 'cycles', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('emoji_notes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_index(op.f('ix_notes_date'), 'notes', ['date'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_date'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_cycles_user_id'), table_name='cycles')
    op.drop_index(op.f('ix_cycles_period_start_date'), table_name='cycles')
    op.drop_table('cycles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
